version: "3.7"
services:
  client:
    image: sharepilot_client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
  server:
    image: sharepilot_server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8081:8081"